apiVersion: apps/v1
kind: Deployment
metadata:
  name: caleb-deployment
  labels:
    app: tech365
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caleb
  template:
    metadata:
      labels:
        app: caleb
    spec:
      containers:
      - name: caleb
        image: 717279705656.dkr.ecr.us-east-1.amazonaws.com/javaapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: caleb-service
  labels:
    app: caleb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: caleb